### PR TITLE
fix: split dockerfile into one per image

### PR DESCRIPTION
**Pull request by GentikSolm**
# Pull Request Title

## Linked GH Issues
None

## Current Behavior
One dockerfile for 3 images

## New Behavior
Each image gets its own dockerfile, with simplified syntax.
Each dockerfile's context is set within the docker compose file
Each image has a simpler interal file struct (/app instead of /app/packages/....)

Im not able to test this locally, make sure you test this out and are sure it works properly!

### CODE REVIEW

**Comment by PudottaPommin** [comment]
1. When you set `context: ./packages/twitch/chat` then you can not do `dockerfile: ./packages/twitch/chat/Dockerfile` but you have to do `dockerfile: Dockerfile`, because **dockerfile** path is relative from **context**.
2. As this is monorepo ( in progress ) you can **not** do `context: ./packages/twitch/chat`, because then Dockerfile won't be able to copy other file outside package directory. So as it is, you prohibited docker from copying file from `packages/settings`.

**Comment by GentikSolm** [comment]
Ah great point. Regardless, there should be separate docker files. To remedy this we can just pull the docker files back to the base dir for the node repo, then just specifically each docker file as need be

**Comment by GentikSolm** [comment]
> 1. When you set `context: ./packages/twitch/chat` then you can not do `dockerfile: ./packages/twitch/chat/Dockerfile` but you have to do `dockerfile: Dockerfile`, because **dockerfile** path is relative from **context**.
> 
>     2. As this is monorepo ( in progress ) you can **not** do `context: ./packages/twitch/chat`, because then Dockerfile won't be able to copy other file outside package directory. So as it is, you prohibited docker from copying file from `packages/settings`.

This should be fixed now. @Geczy you'll need to go in and setup how you want that settings package to be created, but you should be able to use these Dockerfiles much more reasonably now.

**Comment by PudottaPommin** [comment]
@GentikSolm Looks better, but `context` has to be aimed to the root as `context: .`. I chose as example package/settings, but I should have rather use `./node_modules` and `./package.json` for the workspace.

Workspaces ( monorepo ) in a way, that there is global package.json for the repository. In that package.json are common dependencies ( you can say, shared across all projects - typescript, ts-node, eslint, prettier, ... ). Each package then has it's own package.json with package name and their dependencies. For us to be able to build or run certain package, we need both `package.json` files ( package and workspace ). 

If for running application we need `dependencies` which are defined in workspace `package.json`, we also need workspace `node_modules` in our output.

**Pull request closed without merging**
